name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compile docker for arm64
        run: ./compile-docker.sh -a arm64

      - name: Compile docker for armv7
        run: ./compile-docker.sh -a armv7

      - name: Compile docker for armv6
        run: ./compile-docker.sh -a armv6

      - name: Archive tar.xz files
        run: mkdir -p artifacts && mv *.tar.xz artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-tarballs
          path: artifacts/

  release:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-tarballs
          path: artifacts/

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload all tar.xz files
        run: |
          for file in artifacts/*.tar.xz; do
            echo "Uploading $file as release asset..."
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
