name: Renovate Pipeline

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v42.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate-config.json
